//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAcess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book_inventory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Book_inventory()
        {
            this.Book_issue = new HashSet<Book_issue>();
        }
    
        public string book_id { get; set; }
        public string book_name { get; set; }
        public string genre { get; set; }
        public string edition { get; set; }
        public string actual_stock { get; set; }
        public string language { get; set; }
        public string book_cost { get; set; }
        public string pages { get; set; }
        public string description { get; set; }
        public string current_stock { get; set; }
        public string img_link { get; set; }
        public string author_name { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Book_issue> Book_issue { get; set; }
    }
}
